[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss && NODE_OPTIONS='--max-old-space-size=1024' npm run build"

[deploy]
startCommand = "NODE_OPTIONS='--max-old-space-size=512' npm run start"
restartPolicyMaxRetries = 5
