[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyMaxRetries = 5
